#pragma once

ECS_COMPONENT_DECLARE(AINPC);
ECS_COMPONENT_DECLARE(AIPlayer);
ECS_COMPONENT_DECLARE(Animate);
ECS_COMPONENT_DECLARE(BasicAABB);
ECS_COMPONENT_DECLARE(Body);
ECS_COMPONENT_DECLARE(CameraFollow);
ECS_COMPONENT_DECLARE(Menu);
ECS_COMPONENT_DECLARE(MenuItem);
ECS_COMPONENT_DECLARE(PauseMenu);
ECS_COMPONENT_DECLARE(Renderable);
ECS_COMPONENT_DECLARE(TileLayerCollides);
